services:
  mqtt:
    image: eclipse-mosquitto:2
    pull_policy: always
    container_name: mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./app/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "localhost", "-t", "$$SYS/broker/version", "-C", "1", "-W", "3"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: .
    container_name: indoor-backend
    depends_on:
      mqtt:
        condition: service_healthy
    environment:
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped


volumes:
  mosquitto_data:
  mosquitto_log:
